Update studio-macos.sh
This change aims to make the app a tiny bit more user friendly to run on macOS by simply being able to run the `studio-macos.sh` file from the Finder (or from a shortcut on the Dock for example).

Currently, running the `studio-macos.sh` script from anywhere outside the STUdio folder outputs the following errors:

```console
cp: ./agent/studio-agent-0.1.11-jar-with-dependencies.jar: No such file or directory
cp: ./agent/studio-metadata-0.1.11-jar-with-dependencies.jar: No such file or directory
Error: Could not find or load main class io.vertx.core.Launcher
Caused by: java.lang.ClassNotFoundException: io.vertx.core.Launcher
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

Prefixing the problematic paths by the executable path fixes the problem.